data:
  copy: false
env:
  - name: "AWS_ACCESS_KEY_ID"
    value: ${AWS_ACCESS_KEY_ID}
  - name: "AWS_SECRET_ACCESS_KEY"
    value: ${AWS_SECRET_ACCESS_KEY}
  - name: "SEDONA_SOURCE_BUCKET"
    value: ptokaj-sedona-book
