title: Working With Geospatial Data At Scale\:\ Loading Data In Apache Sedona
id: chapter3

sections:
  - title: Loading Vector Data Formats
    id: loading-vector-data-formats
    images:
      - image: sedona
        volumes:
          - chapter3/LoadingVectorDataFormats.ipynb
        browser-path: chapter3/LoadingVectorDataFormats.ipynb
  - title: Introduction To Raster Data Formats (GeoTif)
    id: introduction-to-raster-data-formats-geotif
    images:
      - image: sedona
        volumes:
          - chapter3/LoadingRasterData.ipynb
        browser-path: chapter3/LoadingRasterData.ipynb