title: Working With Geospatial Data At Scale\:\ Loading Data In Apache Sedona
id: chapter3

sections:
  - title: Loading Vector Data Formats
    id: loading-vector-data-formats
    images:
      - image: sedona
        volumes:
          - chapter3/LoadingVectorDataFormats.ipynb
        browser-path: chapter3/LoadingVectorDataFormats.ipynb
  - title: Introduction To Raster Data Formats (GeoTif)
    id: introduction-to-raster-data-formats-geotif
    images:
      - image: sedona
        volumes:
          - chapter3/LoadingRasterData.ipynb
        browser-path: chapter3/LoadingRasterData.ipynb
  - title: Loading Data From Databases
    id: loading-data-from-databases
    images:
      - image: sedona
        volumes:
          - chapter3/ReadingFromPostgreSQL.ipynb
        browser-path: chapter3/ReadingFromPostgreSQL.ipynb
      - image: postgis
        post-init-command:
          - /bin/bash
          - /app/migrate.sh
        browser-path: chapter3/postgis-init.sql
      - image: mysql
        post-init-command:
          - /bin/bash
          - /app/migrate.sh
      - image: mongo
      - image: debezium
        post-init-command:
          - /bin/bash
          - ./create-connector.sh
      - image: kafka