title: "Points, Lines, and Polygons: Vector Data Analysis With Spatial SQL"
id: chapter4

sections:
  - title: "Vector Data Model and Spatial Relationship"
    id: vector-data-model-and-spatial-relationship
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/SpatialRelationships.ipynb
        volumes:
          - chapter4/SpatialRelationships.ipynb:/opt/workspace/SpatialRelationships.ipynb
  - title: "Spatial Reference System and the Geography Model"
    id: spatial-reference-system-and-the-geography-model
  - title: "Spatial SQL and Vector Data Manipulation"
    id: spatial-sql-and-vector-data-manipulation
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/SpatialSQLAndVectorManipulation.ipynb
        volumes:
          - chapter4/SpatialSQLAndVectorManipulation.ipynb:/opt/workspace/SpatialSQLAndVectorManipulation.ipynb
  - title: "Spatial Queries"
    id: spatial-queries
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/SpatialQueries.ipynb
        volumes:
          - chapter4/SpatialQueries.ipynb:/opt/workspace/SpatialQueries.ipynb
  - title: "Hands-On Use Case: Real Estate Analysis"
    id: hands-on-use-case-real-estate-analysis
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/RealEstateAnalysis.ipynb
        volumes:
          - chapter4/RealEstateAnalysis.ipynb:/opt/workspace/RealEstateAnalysis.ipynb
