title: Raster Data Analysis
id: chapter5
sections:
  - title: The Raster Data Model
    id: the-raster-data-model
    images:
      - image: sedona
        volumes:
          - chapter5/RasterModel.ipynb
          - chapter5/images
  - title: Raster SQL and Raster Data Manipulation
    id: raster-sql-and-raster-data-manipulation
    images:
      - image: sedona
        volumes:
          - chapter5/Raster SQL and Raster Data Manipulation.ipynb
          - chapter5/images
  - title: Zonal Statistics
    id: zonal-statistics
    images:
        - image: minio
          post-init-command:
            - /bin/bash
            - /app/sources/scripts/copy_minio.sh
          data:
            - ny_rail_road_and_aviation_noise
            - ny_redfin_sold_offers
          scripts:
            - copy_minio.sh
        - image: sedona
          volumes:
            - chapter5/Zonal Statistics.ipynb
            - chapter5/images
  - title: Map Algebra
    id: map-algebra
    images:
      - image: minio
        post-init-command:
          - /bin/bash
          - /app/sources/scripts/copy_minio.sh
        data:
          - swir_b11_tiles
          - nir_b08_tiles
        scripts:
          - copy_minio.sh
      - image: sedona
        volumes:
          - chapter5/MapAlgebra.ipynb
          - chapter5/images
  - title: Joining raster data with vector data
    id: joining-raster-data-with-vector-data
    images:
      - image: minio
        scripts:
          - copy_minio.sh
        data:
          - world_population_raster
          - fdi_data
        post-init-command:
          - /bin/bash
          - /app/sources/scripts/copy_minio.sh
      - image: sedona
        volumes:
          - chapter5/RasterJoin.ipynb
          - chapter5/images
  - title: Hands-On Use Case\:\ Insurance Risk Modeling
    id: hands-on-use-case-insurance-risk-modeling
    images:
      - image: minio
        post-init-command:
          - /bin/bash
          - /app/sources/scripts/copy_minio.sh
        data:
          - world_population_raster
          - buildings
          - fire_risk
          - flood
          - infrastructure
          - places
        scripts:
          - copy_minio.sh
      - image: sedona
        volumes:
          - chapter5/Use Case Insurance Risk Modeling.ipynb
          - chapter5/images
