title: Apache Sedona And The PyData Ecosystem
id: chapter6
sections:
  - title: Manipulating Geospatial Vector Data
    id: manipulating-geospatial-vector-data
    images:
      - image: minio
        post-init-command:
          - /bin/bash
          - /app/sources/scripts/copy_minio.sh
        data:
          - transportation_barcelona
        scripts:
          - copy_minio.sh
      - image: sedona
        volumes:
          - chapter6/ManipulatingGeospatialVectorData.ipynb
          - chapter6/images
  - title: Transforming your Geospatial Data with dbt
    id: transforming-your-geospatial-data-with-dbt
    images:
      - image: sedonadbt
        volumes:
          - chapter6/images
          - chapter6/geospatialdbt
      - image: thriftserver
