title: Building A Geospatial Data Lakehouse With Apache Parquet And Apache Iceberg
id: chapter8
sections:
  - title: Geospatial Data Lakehouse Deep Dive
    id: geospatial-data-lakehouse-deep-dive
    images:
      - image: airflow
        volumes:
          - chapter8/dags/:/opt/airflow/dags/
        open-webui:
          path: http://localhost:8080
      - image: minio
        volumes:
          - scripts/copy_minio.sh:/app/scripts/copy_minio.sh
          - chapter8/minio:/data
      - image: postgres
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/GeospatialDateLakehouse.ipynb
        volumes:
          - chapter8/GeospatialDateLakehouse.ipynb:/opt/workspace/GeospatialDateLakehouse.ipynb
