# spark executor settings
spark.driver.memory 4g
spark.executor.memory 4g

# sedona bucket
spark.hadoop.fs.s3a.bucket.ptokaj-sedona-book.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.bucket.ptokaj-sedona-book.access.key <AWS_ACCESS_KEY_ID>
spark.hadoop.fs.s3a.bucket.ptokaj-sedona-book.secret.key <AWS_SECRET_ACCESS_KEY>

# iceberg properties
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.sql.catalog.sedona_catalog org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.sedona_catalog.warehouse s3a://apache-sedona-book/data
spark.sql.catalog.sedona_catalog.type jdbc
spark.sql.catalog.sedona_catalog.uri jdbc:postgresql://postgres:5432/sedona
spark.sql.catalog.sedona_catalog.jdbc.verifyServerCertificate true
spark.sql.catalog.sedona_catalog.jdbc.useSSL true
spark.sql.catalog.sedona_catalog.jdbc.user sedona
spark.sql.catalog.sedona_catalog.jdbc.password sedona

# minio bucket
spark.hadoop.fs.s3a.bucket.apache-sedona-book.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.bucket.apache-sedona-book.access.key sedona
spark.hadoop.fs.s3a.bucket.apache-sedona-book.secret.key sedona_password
spark.hadoop.fs.s3a.bucket.apache-sedona-book.path.style.access true
spark.hadoop.fs.s3a.bucket.apache-sedona-book.endpoint http://minio:9000

# unlock sedona
spark.sql.extensions org.apache.sedona.viz.sql.SedonaVizExtensions,org.apache.sedona.sql.SedonaSqlExtensions
