CREATE TABLE IF NOT EXISTS {catalog}.{database}.nl_road_risk_score (
    H3 STRING,
    GEOMETRY BINARY,
    RISK_SCORE DOUBLE,
    PROCESSING_DATE DATE
)
USING ICEBERG
PARTITIONED BY(DATE(PROCESSING_DATE))