CREATE TABLE IF NOT EXISTS {catalog}.{database}.nl_transportation (
    ID STRING,
    GEOMETRY BINARY,
    MAX_SPEED ARRAY<INT>,
    PROCESSING_DATE DATE
)
USING ICEBERG
PARTITIONED BY(DATE(PROCESSING_DATE))