CREATE TABLE IF NOT EXISTS {catalog}.{database}.nl_transportation_hex_bins (
    H3 STRING,
    SPEED_LIMIT INT,
    GEOMETRY BINARY,
    PROCESSING_DATE DATE
)
USING ICEBERG
PARTITIONED BY(DATE(PROCESSING_DATE))